language: scala
sudo: false

scala:
- 2.11.8

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
- curl -sL -o consul.zip https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
- unzip consul.zip
- ./consul agent -dev > /dev/null &

sbt_args: -J-Xmx2g

script:
- sbt ++$TRAVIS_SCALA_VERSION "+ test"
